Repository prgrms-fdc-2nd-final-mosdaq/mosdaq-back, pull requests merged in 2024-08, with the labels that each got.

#6 Feature/#5 메인페이지 대표 영화 api
  package-lock.json
  package.json
  src/app.controller.ts
  src/app.module.ts
  src/main.ts
  src/main/entities/main-movie-view.entity.ts
  src/main/main.controller.spec.ts
  src/main/main.controller.ts
  src/main/main.module.ts
  src/main/main.service.spec.ts
  src/main/main.service.ts
Labels: Feature

#12 Feature/#8 구글 OAuth 로그인, 로그아웃, 토큰재발급, 유저 정보 조회
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/accessToken.guard.ts
  src/auth/auth.controller.spec.ts
  src/auth/auth.controller.ts
  src/auth/auth.guard.ts
  src/auth/auth.module.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/auth/dto/googleOAuth.dto.ts
  src/auth/dto/refreshAuthToken.dto.ts
  src/auth/google.strategy.ts
  src/main.ts
  src/users/entities/users.entity.ts
  src/users/users.controller.spec.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
Labels: Feature

#13 feat: 영화 퀴즈 목록 요청 api
  src/app.module.ts
  src/movie-quiz/entities/movie-quiz.entity.ts
  src/movie-quiz/movie-quiz.controller.spec.ts
  src/movie-quiz/movie-quiz.controller.ts
  src/movie-quiz/movie-quiz.module.ts
  src/movie-quiz/movie-quiz.service.spec.ts
  src/movie-quiz/movie-quiz.service.ts
Labels: Feature

#36 feat: cors with config
  src/main.ts
Labels: Feature

#30 FEATURE/#29 .env.example 파일 추가
  .env.example
Labels: documentation

#40 FEATURE/#21 투표 마감된 영화 목록, 투표 인기순
  package-lock.json
  package.json
  src/app.module.ts
  src/main.ts
  src/main/dto/popular-movie-polled-response.dto.ts
  src/main/entities/main-movie-view.entity.ts
  src/main/entities/popular-movie-polled-view.entity.ts
  src/main/entities/popular-movie-polling-view.entity.ts
  src/main/main.controller.ts
  src/main/main.module.ts
  src/main/main.service.ts
  src/users/users.controller.ts
Labels: Feature

#52 FEATURE/#51 유저 상위 n%
  src/auth/auth.controller.ts
  src/users/dto/userInfo.dto.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: Feature

#42 Feature/#41 aws 배포 개발용 임시 cors설정
  src/main.ts
Labels: Feature

#56 REFACTOR/#54 응답 값의 posturl '|' 단위로 잘라서 전달
  src/main/dto/popular-movie-polled-response.dto.ts
  src/main/entities/main-movie-view.entity.ts
  src/main/entities/popular-movie-polling-view.entity.ts
  src/main/main.service.ts
Labels: enhancement

#55 REFACTOR/#20 entity 내부 snake_case -> camelcase
  src/main/entities/main-movie-view.entity.ts
  src/main/entities/popular-movie-polling-view.entity.ts
  src/main/main.service.ts
Labels: enhancement

#60 FEATURE/#37 영화 투표하기
  package-lock.json
  package.json
  src/app.module.ts
  src/constants/app.constants.ts
  src/constants/index.ts
  src/main.ts
  src/main/entities/popular-movie-polled-view.entity.ts
  src/main/main.controller.ts
  src/main/main.module.ts
  src/main/main.service.ts
  src/poll/dto/do-poll.dto.ts
  src/poll/entities/movie.entity.ts
  src/poll/entities/poll.entity.ts
  src/poll/poll.controller.spec.ts
  src/poll/poll.controller.ts
  src/poll/poll.module.ts
  src/poll/poll.service.spec.ts
  src/poll/poll.service.ts
  src/users/users.controller.ts
  src/util/swagger/setupSwagger.ts
Labels: Feature

#62 fix : 영화 퀴즈 목록 api 수정
  package-lock.json
  package.json
  src/movie-quiz/dto/get-movie-quiz.dto.ts
  src/movie-quiz/dto/movie-quiz.dto.ts
  src/movie-quiz/entities/movie-quiz.entity.ts
  src/movie-quiz/movie-quiz.controller.ts
  src/movie-quiz/movie-quiz.service.ts
Labels: bugfix

#63 fix : movie poster 파이프 분리
  src/movie-quiz/movie-quiz.service.ts
Labels: bugfix

#70 feat: 영화 상세정보 조회 api 구현
  src/app.module.ts
  src/movie-detail/dto/movie-detail.dto.ts
  src/movie-detail/movie-detail.controller.spec.ts
  src/movie-detail/movie-detail.controller.ts
  src/movie-detail/movie-detail.module.ts
  src/movie-detail/movie-detail.service.spec.ts
  src/movie-detail/movie-detail.service.ts
  src/movie-quiz/movie-quiz.controller.ts
Labels: Feature

#75 FEATURE/#46 투표 영화 목록
  src/app.module.ts
  src/constants/app.constants.ts
  src/constants/index.ts
  src/constants/swagger.constants.ts
  src/movie-list/dto/poll-movie-list-response.dto.ts
  src/movie-list/entities/movie-list.entity.ts
  src/movie-list/movie-list.controller.spec.ts
  src/movie-list/movie-list.controller.ts
  src/movie-list/movie-list.module.ts
  src/movie-list/movie-list.service.spec.ts
  src/movie-list/movie-list.service.ts
  src/poll/entities/movie.entity.ts
  src/poll/poll.controller.ts
Labels: Feature

#79 feat: 투표함 가져오기 API 구현
  src/auth/optionalAccessToken.guard.ts
  src/poll/dto/poll-box.dto.ts
  src/poll/poll.controller.ts
  src/poll/poll.service.ts
Labels: Feature

#82 FEATURE/#80 getUserPollMovies controller 추가
  src/movie-list/dto/poll-movie-list-response.dto.ts
  src/movie-list/movie-list.controller.ts
  src/users/dto/user-poll-movie-list-response.dto.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: Feature

#91 feat: 퀴즈 response 회사명 추가
  src/movie-quiz/dto/movie-quiz.dto.ts
  src/movie-quiz/movie-quiz.controller.ts
  src/movie-quiz/movie-quiz.service.ts
Labels: Feature, Refactor

#97 [FEATURE] 커스텀 User 데코레이터, accessToken - Jwt 가드 수정
  src/auth/Jwt/JwtAuth.guard.ts
  src/auth/Jwt/accessToken.guard.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/google.auth.guard.ts
  src/poll/dto/do-poll.dto.ts
  src/poll/poll.controller.ts
  src/poll/poll.module.ts
  src/poll/poll.service.ts
  src/users/dto/JwtUser.dto.ts
  src/users/users.controller.ts
  src/users/users.decorator.ts
Labels: Feature, fix

#98 REFACTOR/#92 메인페이지 대표 영화 api 수정
  src/constants/app.constants.ts
  src/main/dto/main-movie-response.dto.ts
  src/main/entities/main-movie-view.entity.ts
  src/main/main.controller.ts
  src/main/main.service.ts
  src/util/date.ts
Labels: enhancement

#102 REFACTOR/#101 메인페이지 배너 api 수정
  src/main/dto/main-movie-response.dto.ts
  src/main/entities/main-movie-view.entity.ts
  src/main/main.service.ts
Labels: enhancement

#106 [FEATURE] 배너 movieOpenDate 추가
  src/main/dto/main-movie-response.dto.ts
  src/main/main.service.ts
Labels: Feature

#109 FEATURE/#94 영화 목록, user id 정보 추가하여 service 호출
  src/movie-list/movie-list.controller.ts
  src/movie-list/movie-list.module.ts
  src/movie-list/movie-list.service.ts
Labels: enhancement

#111 FEATURE/#83 마이페이지 투표한 영화 투표 마감된 영화 목록
  src/movie-list/movie-list.controller.ts
  src/poll/entities/movie.entity.ts
  src/stocks/entities/company.entity.ts
  src/stocks/entities/stock.entity.ts
  src/users/dto/user-poll-movie-list-response.dto.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: Feature

#116 [FEATURE] 프로필 사진
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/google.strategy.ts
  src/users/dto/userInfo.dto.ts
  src/users/entities/users.entity.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: Feature

#118 REFACTOR/#114 Jwt 디렉터리 소문자로 변경(jwt)
  src/auth/jwt/JwtAuth.guard.ts
  src/auth/jwt/accessToken.guard.ts
Labels: Refactor

#119 FEATURE/#35 config 모듈 추가
  nest-cli.json
  package-lock.json
  package.json
  src/app.module.ts
  src/config/dbConfig.ts
  src/config/env/.env.development.local.example
  src/config/env/.env.production.local.example
  src/config/env/.env.test.local.example
  src/config/validationSchema.ts
  src/main.ts
  src/users/dto/user-poll-movie-list-parameter.dto.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: Feature

#120 FEATURE/#117 투표마감 영화 목록(인기순) 응답 수정
  src/constants/app.constants.ts
  src/main/dto/popular-movie-polled-response.dto.ts
  src/main/main.controller.ts
  src/main/main.service.ts
Labels: enhancement

#123 [REFACTOR] 영화 상세정보 배너처럼 주가 데이터 내려주기
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/dto/google-OAuth.dto.ts
  src/auth/dto/refresh-auth-token.dto.ts
  src/auth/dto/token-response.dto.ts
  src/auth/jwt/access-token.guard.ts
  src/auth/jwt/jwt-auth.guard.ts
  src/auth/optionalAccessToken.guard.ts
  src/config/env/.env.development.local.example
  src/config/env/.env.production.local.example
  src/config/env/.env.test.local.example
  src/main/main.controller.ts
  src/movie-list/movie-list.controller.ts
  src/poll/poll.controller.ts
  src/poll/poll.service.ts
  src/stocks/dto/stock-info-by-movieId.dto.ts
  src/stocks/stocks.controller.ts
  src/stocks/stocks.service.ts
  src/users/dto/jwt-user.dto.ts
  src/users/dto/user-info.dto.ts
  src/users/users.controller.ts
Labels: Refactor

#127 feat: cors 정책에 프론트엔드 도메인 추가
  src/main.ts
  src/users/users.service.ts
Labels: Feature

#131 feat: response에 companyName 추가 및 poster 명칭 수정
  src/movie-detail/dto/movie-detail.dto.ts
  src/movie-detail/movie-detail.controller.ts
  src/movie-detail/movie-detail.service.ts
Labels: Feature, Refactor
